-- Default-close Supabase public API access.
-- The Loopin API uses the server-side Postgres connection through Prisma; public Supabase REST access is not part of the product path.

REVOKE ALL ON SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon, authenticated;

ALTER TABLE public."AgentTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AttributionEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BudgetPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Channel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CheckIn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EventFeedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EventPage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EventResource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EventReview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."EventSocialProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."HostProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."InterestSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Material" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."NotificationSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Organizer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."OrganizerMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Quota" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Registration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."RegistrationForm" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SponsorPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TicketType" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TicketTypeQuota" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."TopicSignal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."WaitlistEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."_prisma_migrations" ENABLE ROW LEVEL SECURITY;
